### ISSUE TITLE
proposal: deflate

### ISSUE THREAD

**Issue by ah8ad3** [friedelwolff/django-compression-middleware#2]
hi
i am interested to you're project 
i want to implement deflate 
can i ?

**Comment by friedelwolff** [comment]
Thank you for your interest in the project!

I am busy writing an FAQ for the next release, and I have a draft for a question about deflate. This is what it looks like at the moment:

> The deflate algorithm provides very little benefit over gzip in terms of compression — it is actually the same algorithm, but using 11 bytes less overhead. Due to historical incompatibilities most people prefer gzip over deflate. There is no realistic chance today of a client supporting deflate that doesn't also support gzip.

I hope that gives a clear picture of my thinking. This is also what I found with several other web servers.

I am not aware of any web client that supports deflate without also supporting gzip. Please say if you are aware of such a client. I'm closing this issue based on this reasoning, but we can reopen if new information becomes available.

**Comment by friedelwolff** [comment]
I added the FAQ that I mentioned. Please say if you feel it can be improved.

For now I'm marking this as "wontfix", but it can be revisited if new information comes to light.
