### ISSUE TITLE
Media files served with 0 length when used?

### ISSUE THREAD

**Issue by embeddedt** [friedelwolff/django-compression-middleware#9]
When the middleware is added to my Django project, media files (MEDIA_URL) are empty. The browser shows that the response has 0 length. Removing the middleware fixes the issue.

Here is the list of middleware I am using:

```
MIDDLEWARE = [
    'compression_middleware.middleware.CompressionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

**Comment by friedelwolff** [comment]
Thank you for the report. What kind of request triggered the problem? Can you provide a minimal example that will indicate the setup I need to investigate?

**Comment by embeddedt** [comment]
It was just a GET request to display a PNG file. I didn't try with JPEGs but I assume they have the same issue. Other requests for HTML, JavaScript, and CSS work without problems.

I will make a full example in a few days.
